services:
  postgres:
    container_name: postgres-arregloya
    image: postgres
    environment:
      POSTGRES_DB: arregloya
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - 5400:5432
    networks:
      - spring-demo
    restart: always
  mail-dev:
    container_name: mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local